In [2]:
import numpy as np
import pandas as pd

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

### First, generate a 30x5 feature matrix

In [3]:
X = np.random.normal(size=(30,5))
X

array([[ 0.67289971,  0.86903318,  0.07650392, -1.27018742, -1.06108953],
       [ 1.2741942 , -1.88463695, -1.16508105,  0.1216687 ,  0.18646844],
       [-1.41975397, -0.19928164, -0.49685842, -0.16242298,  1.67199221],
       [ 0.72887953, -0.32836363, -1.02825918, -0.84124152, -0.92613098],
       [-0.24481976,  0.54322327,  0.75617357, -0.65366122, -0.41406388],
       [ 0.63577057, -0.10971435, -0.6949495 ,  0.2900648 , -0.2564844 ],
       [-0.23875481,  1.32129492, -0.01298545,  0.6422868 ,  0.71197931],
       [ 0.34520116, -0.30234126, -0.6644053 , -0.71085191, -0.7328019 ],
       [ 2.95189746,  1.3848844 , -1.51987807, -1.8107577 , -0.49337553],
       [-0.47777194, -0.29342404, -0.58758611, -0.42231755,  0.15498524],
       [ 0.06076858, -0.18899883, -0.08471123,  0.62594904, -0.24737879],
       [-0.47441421, -1.68644032,  2.87966818,  0.3207804 ,  0.9989429 ],
       [-0.51925264,  0.68361561, -0.61191034, -0.97632402, -0.923273  ],
       [-0.32420742, -0.35988267, -0.3

### Because PCA works on centered data, apply standard normalization

Going forward, I will refer to this matrix as the original feature matrix. I just wanted to emphasize that the data __must__ be centered

In [4]:
ss = StandardScaler()
X_standardized = ss.fit_transform(X)
X_standardized

array([[ 0.51836412,  0.92794617,  0.24361577, -1.19244999, -0.81249607],
       [ 1.08835972, -1.99077353, -1.03755485,  0.13849943,  0.3312615 ],
       [-1.46536167, -0.20440134, -0.34802717, -0.13316059,  1.69318544],
       [ 0.57143005, -0.34122025, -0.89637066, -0.78227448, -0.68876646],
       [-0.35158574,  0.58260785,  0.94495544, -0.60290257, -0.2193048 ],
       [ 0.48316765, -0.10946557, -0.55243401,  0.29952662, -0.07483639],
       [-0.34583649,  1.40731558,  0.1512732 ,  0.63633562,  0.81304837],
       [ 0.20772311, -0.31363815, -0.52091597, -0.65759063, -0.51152291],
       [ 2.67873431,  1.47471649, -1.40366391, -1.70936528, -0.29201749],
       [-0.57241217, -0.30418645, -0.44164754, -0.38168235,  0.3023978 ],
       [-0.06190404, -0.1935022 ,  0.07726058,  0.62071279, -0.06648839],
       [-0.56922922, -1.78069738,  3.13615376,  0.32889813,  1.07613576],
       [-0.6117337 ,  0.73141503, -0.4667473 , -0.91144586, -0.68614627],
       [-0.42684107, -0.37462848, -0.1

### Fit the feature matrix using PCA

In [5]:
pca = PCA()
pca.fit(X_standardized)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

### Examine the attributes of PCA object.

In [9]:
print(pca.components_.shape)
pca.components_

(5, 5)


array([[-0.2671856 , -0.72064448,  0.63415564, -0.00665089,  0.08417702],
       [ 0.53795794,  0.02314233,  0.34392122,  0.40632839, -0.65320833],
       [ 0.51051985, -0.21424192, -0.02215927, -0.82489325, -0.11193739],
       [ 0.47466847,  0.2875738 ,  0.43503594,  0.11239376,  0.70007323],
       [ 0.39150024, -0.59290612, -0.53834702,  0.37652593,  0.25219159]])

In [10]:
print(pca.explained_variance_.shape)
pca.explained_variance_

(5,)


array([ 1.30063273,  1.25281856,  1.05966967,  0.88689668,  0.67239615])

### What do these attributes mean, and how is it used for PCA?

- pca.components\_ is the matrix transformation that gets applied to the features to move them to the componenent space. This matrix is the eigenvectors found while diagonalizing the covariance matrix of the features. The diagonalized covariance matrix is the covariance of the components.
- pca.explained\_variance\_ are the eigenvalues for the corresponding eigenvectors. The first component is the one with the largest eigenvalue, and they are sorted in descending order

### Transform features to components

Notice that features mapped to the component space have the same dimensions as the original features matrix. No dimensions have been reduced at this point. We've simply started describing the features using a new coordinate system. The description of this coordinate system are the vectors stored in pca.components\_. And again, these are simply the eigenvectors calculated such that the covariance matrix of the original features become diagonalized.

In [13]:
X_transformed = pca.transform(X_standardized)
print(X_transformed.shape)
X_transformed

(30, 5)


array([[ -7.13191037e-01,   4.30320479e-01,   1.13502449e+00,
         -8.39449659e-02,  -1.13228813e+00],
       [  5.12838114e-01,   2.24769698e-02,   8.53800060e-01,
         -2.59784138e-01,   2.30068946e+00],
       [  4.61533782e-01,  -2.07283696e+00,  -7.76280346e-01,
          2.64641607e-01,   1.11729467e-01],
       [ -5.27993385e-01,   1.23275469e-01,   1.10708465e+00,
         -7.86949360e-01,   4.40337310e-01],
       [  2.58883753e-01,   4.76100810e-02,   1.96628615e-01,
          1.90453757e-01,  -1.27410689e+00],
       [ -4.08830451e-01,   2.37986728e-01,   4.36598276e-02,
         -6.11896610e-02,   6.45370696e-01],
       [ -7.61633136e-01,  -3.73979599e-01,  -1.09733396e+00,
          9.47072254e-01,  -6.06597742e-01],
       [ -1.98505730e-01,  -7.73279440e-03,   7.84484942e-01,
         -6.50224253e-01,   1.71113481e-01],
       [ -2.68181928e+00,   4.88609587e-01,   2.52543666e+00,
          6.88400665e-01,   2.12750255e-01],
       [  1.20070768e-01,  -8.1948235

### Covariance Matrix

Take a look at the covariance matrix of the original feature matrix and of the features mapped to the component space

In [18]:
covar = np.round(np.cov(X_standardized.T),6)
covar

array([[ 1.034483,  0.115112,  0.040853, -0.023657, -0.168941],
       [ 0.115112,  1.034483, -0.253811,  0.083844,  0.005587],
       [ 0.040853, -0.253811,  1.034483,  0.096028, -0.030569],
       [-0.023657,  0.083844,  0.096028,  1.034483, -0.101769],
       [-0.168941,  0.005587, -0.030569, -0.101769,  1.034483]])

In [19]:
new_covar = np.round(np.cov(X_transformed.T),6)
new_covar

array([[ 1.300633,  0.      ,  0.      , -0.      ,  0.      ],
       [ 0.      ,  1.252819, -0.      , -0.      , -0.      ],
       [ 0.      , -0.      ,  1.05967 , -0.      , -0.      ],
       [-0.      , -0.      , -0.      ,  0.886897,  0.      ],
       [ 0.      , -0.      , -0.      ,  0.      ,  0.672396]])

Notice that while the covariance matrix has been transformed, the sum of the diagonals (aka trace) is the same.

In [20]:
print(np.trace(covar))
print(np.trace(new_covar))

5.172415
5.172415


Keep in mind that the diagonal of the covariance matrix shows the amount of variance that each components captures. The goal of PCA is to redistribute the variation into as few components as possible.

### Manual Matrix Multiplication

In [21]:
np.matmul(X_standardized, pca.components_.T)

array([[ -7.13191037e-01,   4.30320479e-01,   1.13502449e+00,
         -8.39449659e-02,  -1.13228813e+00],
       [  5.12838114e-01,   2.24769698e-02,   8.53800060e-01,
         -2.59784138e-01,   2.30068946e+00],
       [  4.61533782e-01,  -2.07283696e+00,  -7.76280346e-01,
          2.64641607e-01,   1.11729467e-01],
       [ -5.27993385e-01,   1.23275469e-01,   1.10708465e+00,
         -7.86949360e-01,   4.40337310e-01],
       [  2.58883753e-01,   4.76100810e-02,   1.96628615e-01,
          1.90453757e-01,  -1.27410689e+00],
       [ -4.08830451e-01,   2.37986728e-01,   4.36598276e-02,
         -6.11896610e-02,   6.45370696e-01],
       [ -7.61633136e-01,  -3.73979599e-01,  -1.09733396e+00,
          9.47072254e-01,  -6.06597742e-01],
       [ -1.98505730e-01,  -7.73279440e-03,   7.84484942e-01,
         -6.50224253e-01,   1.71113481e-01],
       [ -2.68181928e+00,   4.88609587e-01,   2.52543666e+00,
          6.88400665e-01,   2.12750255e-01],
       [  1.20070768e-01,  -8.1948235

Consider what happening here intuitively with matrix multiplication. Each value in the first row of the original feature matrix gets multiplied by its correspoding value of the first column of pca.components\_. The first and first column are used to calculate the value of the first component. That same row then gets multiplied by the second component, then the third, to calculate the value of all components for that first row. The reduction in dimensions occurs when a user __chooses__ the number of dimension to reduce to and takes the first k components.

### Reduced Components

So for example, we now fit and reduce to 3 "principal" components

In [25]:
pca_red = PCA(n_components=3)
pca_red.fit(X_standardized)
X_trans_red = pca_red.transform(X_standardized)
X_trans_red

array([[-0.71319104,  0.43032048,  1.13502449],
       [ 0.51283811,  0.02247697,  0.85380006],
       [ 0.46153378, -2.07283696, -0.77628035],
       [-0.52799338,  0.12327547,  1.10708465],
       [ 0.25888375,  0.04761008,  0.19662861],
       [-0.40883045,  0.23798673,  0.04365983],
       [-0.76163314, -0.3739796 , -1.09733396],
       [-0.19850573, -0.00773279,  0.78448494],
       [-2.68181928,  0.48860959,  2.52543666],
       [ 0.12007077, -0.81948235,  0.06372587],
       [ 0.1952563 ,  0.2844357 , -0.49643825],
       [ 3.51254764,  0.16185877, -0.37036335],
       [-0.71133003, -0.39483453,  0.36999178],
       [ 0.3654623 , -1.12068864, -0.20927746],
       [-1.39569317,  0.27284369, -0.82420457],
       [-0.18028271,  0.3684298 , -0.87445521],
       [-0.46828156, -0.75342366, -1.58713169],
       [ 1.05491232, -0.38184056, -0.88152974],
       [-0.05692793,  1.84135304, -0.16558426],
       [ 0.95995039, -0.19251044,  0.61192262],
       [ 1.89723517,  1.58386011,  1.762

In [24]:
print(pca_red.components_.shape)
pca_red.components_

(3, 5)


array([[-0.2671856 , -0.72064448,  0.63415564, -0.00665089,  0.08417702],
       [ 0.53795794,  0.02314233,  0.34392122,  0.40632839, -0.65320833],
       [ 0.51051985, -0.21424192, -0.02215927, -0.82489325, -0.11193739]])

Notice the shape of pca\_red.components\_. The number of rows have been reduced (note we transpose components when we matrix multiply. This is just the way that numpy stores matrices).

In [26]:
np.matmul(X_standardized, pca_red.components_.T)

array([[-0.71319104,  0.43032048,  1.13502449],
       [ 0.51283811,  0.02247697,  0.85380006],
       [ 0.46153378, -2.07283696, -0.77628035],
       [-0.52799338,  0.12327547,  1.10708465],
       [ 0.25888375,  0.04761008,  0.19662861],
       [-0.40883045,  0.23798673,  0.04365983],
       [-0.76163314, -0.3739796 , -1.09733396],
       [-0.19850573, -0.00773279,  0.78448494],
       [-2.68181928,  0.48860959,  2.52543666],
       [ 0.12007077, -0.81948235,  0.06372587],
       [ 0.1952563 ,  0.2844357 , -0.49643825],
       [ 3.51254764,  0.16185877, -0.37036335],
       [-0.71133003, -0.39483453,  0.36999178],
       [ 0.3654623 , -1.12068864, -0.20927746],
       [-1.39569317,  0.27284369, -0.82420457],
       [-0.18028271,  0.3684298 , -0.87445521],
       [-0.46828156, -0.75342366, -1.58713169],
       [ 1.05491232, -0.38184056, -0.88152974],
       [-0.05692793,  1.84135304, -0.16558426],
       [ 0.95995039, -0.19251044,  0.61192262],
       [ 1.89723517,  1.58386011,  1.762

Note that this makes sense in terms of matrix multiplication. Using the transposed components\_ table -- each row of components\_ multiplies with each itme of each row in the original matrix. There are three columns of components